package bean;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cotizacion.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//

public class CotizacionDTO {
	private int id;
//	private Vector<ItemCotizacionDTO> items;
	private String estado;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getEstado() {
		return estado;
	}
	public void setEstado(String estado) {
		this.estado = estado;
	}	
}