package bean;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rodamiento.java
//  @ Date : 9/16/2015
//  @ Author : 

public class RodamientoDTO {
	private int id;
	private String codigoSKF;
	private String tipo;

	public String getCodigoSKF() {
		return codigoSKF;
	}
	public void setCodigoSKF(String codigoSKF) {
		this.codigoSKF = codigoSKF;
	}
	public String getTipo() {
		return tipo;
	}
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
}