package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bulto.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class Bulto {
	public String codigo;
	public void agregarRodamientoComprado(Rodamiento rodamientoComprado) {
	
	}
}
