package Entities;

import java.util.Vector;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CCentral.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//

public class CCentral {
	private CCentral instancia; //se le pone el  (singleton) ???;

	private Vector<Proveedor> proveedores;
	private Vector<Bulto> bultos;

	/*
	public void altaProveedor(  ProveedorDTO) {

	}

	public void bajaProveedor(  ProveedorDTO) {

	}

	public void modificacionProveedor(  ProveedorDTO) {

	}
	

	public CotizacionDTO crearCotizacion() {
		return null;
	}
	*/

	public void crearOC() {

	}

	public void ActualizarStock(  String codigoSKF,   int cantidad,   float precio) {
	
	}

	private Rodamiento buscarRodamiento(  String codigoSKF) {
	
		return null;
	}
	
	/*
	public void GenerarBultosDeRodamiento(  ListasRemitos remitosOV,   ListaRodamientos rodamientosComprados) {
	
	}

	public listasXML generarOrdenesDeCompra(  PedVenta pedidos) {
	
	}
	*/
	public void PublicarListaDePreciosFinal() {
	
	}

	/*
	public void generarListaDePrecioProveedorAutomatica(  XML archivoProveedor,   int codigoProveedor) {
	
	}*/

	public Proveedor buscarProveedor(  int codigoProveedor) {
	
		return null;
	}
}
