package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class Cliente {
	public String codigo;
}
