package Entities;

import java.util.Vector;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ComparativaPrecios.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class ComparativaPrecios {
	private ComparativaPrecios instancia; //Se le pone el singleton en algun lado? singleton;
	private Vector<ItemPrecios> items;
	public void getMejorPrecio() {
	
	}
	
	public ItemPrecios buscarRodamiento(String codigoSKF) {
		return null;
	}
	
	public void ActualizarPrecio(  Proveedor proveedor,   ItemProveedor itemProveedorFinal) {
	
	}
}
