package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CondCompra.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class CondCompra {
	private String descripcion;
	private float porcentaje;
}
