package Entities;

import java.util.Vector;

import Dao.CotizacionDAO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cotizacion.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//

public class Cotizacion {
	private Vector<ItemCotizacion> items;
	private String estado;

	public void agregarItem(Rodamiento rod, int cant) {

	}

	public void aceptar() {
		this.estado = "Aceptada";
		CotizacionDAO.saveEntity(this);
	}

	public float getTotal() {
		return 0;
	}

	public Vector<ItemCotizacion> getItems() {
		return items;
	}

	public void setItems(Vector<ItemCotizacion> items) {
		this.items = items;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
}
