package Entities;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Envio.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class Envio {
	public Cliente cli;
	public Date fecha;
	public void agregarItem(Rodamiento rod, int cant) {
	
	}
}
