package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Factura.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class Factura {
	public Cliente cli;
	public PedVenta pedido;
	public float getTotal() {
		return 0;
	}
}
