package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FormaPago.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class FormaPago {
	private String descripcion;
	private float porcentaje;
	private int cuotas;
	private int dias;
	private boolean activa;
}
