package Entities;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemRemito.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class ItemRemito {
	private int cantidad;
	private Rodamiento rodamiento;
}
