package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemCotizacion.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class ItemCotizacion {
	public int cantidad;
	public Rodamiento rod;
	public float precio;
	public float getSubtotal() {
		return 0;
	}
}
