package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemPedVenta.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class ItemPedVenta {
	private Rodamiento rodamiento;
	private int cantidad;
	public float precio;
	public Rodamiento getRodamiento() {
		return null;
	}
	
	public float getSubTotal() {
		return 0;
	}
}
