package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemProveedor.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class ItemProveedor {
	private String codigo;
	private float precio;
	private String condiciones;
	private boolean disponible;
	private Rodamiento rodamiento;
	public boolean existeRodamiento(  String codigoSKF) {
	
		return true;
	}
	
	public void actualizarCantidad(  Rodamiento rodamiento,   int cantidad) {
	
	}
	
	public void sosElRodamiento(  Rodamiento rodamiento) {
	
	}
	
	public void actualizar(  float precio,   String condiciones,   boolean disponible,   Rodamiento rodamiento) {
	
	}
}
