package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemEnvio.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class ItemEnvio {
	public int cantidad;
	public Rodamiento rod;
}
