package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemCotizacion.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//

public class ItemCotizacion
{
	public int cantidad;
	public Rodamiento rod;
	public float precio;
	
	public float getSubtotal()
	{
		return this.cantidad * this.precio;
	}
	
	public int getCantidad()
	{
		return cantidad;
	}
	
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
	}
	
	public Rodamiento getRod()
	{
		return rod;
	}
	
	public void setRod(Rodamiento rod)
	{
		this.rod = rod;
	}
	
	public float getPrecio()
	{
		return precio;
	}
	
	public void setPrecio(float precio)
	{
		this.precio = precio;
	}
}