package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemPrecios.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class ItemPrecios {
	private Rodamiento rodamiento;
	private String codRodProv;
	private Proveedor proveedor;
	private float precio;
	public void actualizar(Proveedor proveedor, ItemProveedor itemProveedor) {
	
	}
}
