package Entities;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ListaPrecios.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class ListaPrecios {
}
