package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OCProveedor.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class OCProveedor {
	private Proveedor proveedor;
	public String codigo;
	public void agregarAOC(Rodamiento rodamiento, int cantidad) {
	
	}
	
	public Rodamiento buscarRodamientoEnOC(String SKF) {
	
		return null;
	}
}
