package Entities;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OVenta.java
//  @ Date : 9/16/2015
//  @ Author : 
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import bean.CotizacionDTO;

@Entity
public class OVenta {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public String codigo;

	@Column(nullable = false, length = 50)
	public String nombre;

	@Column(nullable = false, length = 50)
	public String direccion;

	public void generarCotizacion() {

	}

	public void generarXMLCotizacion() {

	}

	public void aceptarCotizacion(CotizacionDTO cotDTO) {
		// Cotizacion cot = CotizacionDAO.getEntidad(cotDTO.getId(),
		// Cotizacion.class.toString());

		// if (cot != null) {
		// cot.aceptar();
		// }
	}

	public PedVenta getPedidosVenta() {

		return null;
	}

	public void crearEnvio() {

	}

	public void buscarCliente() {

	}

	public void buscarRodamiento(String codSKF) {

	}

	public void addRodamiento(Rodamiento rod) {

	}

	public void generarFactura(Cliente cli, PedVenta ped) {

	}
}
