package Entities;

import bean.CotizacionDTO;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OVenta.java
//  @ Date : 9/16/2015
//  @ Author : 

public class OVenta {
	public String codigo;

	public void generarCotizacion() {

	}

	public void generarXMLCotizacion() {

	}

	public void aceptarCotizacion(CotizacionDTO cotDTO) {
		Cotizacion cot = CotizacionDAO.getEntidad(cotDTO.getId(), Cotizacion.class.toString());

		if (cot != null) {
			cot.aceptar();
		}
	}

	public PedVenta getPedidosVenta() {

		return null;
	}

	public void crearEnvio() {

	}

	public void buscarCliente() {

	}

	public void buscarRodamiento(String codSKF) {

	}

	public void addRodamiento(Rodamiento rod) {

	}

	public void generarFactura(Cliente cli, PedVenta ped) {

	}
}
