package Entities;

import java.util.Vector;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PedVenta.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class PedVenta {
	private Cotizacion cotizacion;
	private Vector<ItemPedVenta> items;
	public Vector<ItemPedVenta> getItems() {
		return null;
	}
	
	public float getTotal() {
		return 0;
	}
}
