package Entities;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Remito.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class Remito {
	public String codigo;
	public Date fecha;
	
	public boolean contieneRodamiento(Rodamiento rodamientoComprado) {
	
		return true;
	}
}
