package Entities;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Stock.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//




public class Stock {
	private int cantidad;
	private float precio;
}
