package RMI;

import java.util.Vector;

import Entities.CCentral;
import Entities.OVenta;
import Entities.PedVenta;
import Entities.Rodamiento;
import bean.RodamientoDTO;

//

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sistema.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//

public class Sistema
{
	private CCentral cc; // VA ESTO NO ?
	private Vector<RodamientoDTO> rodamientosDTO;
	private Vector<Rodamiento> rodamientos;
	private Vector<PedVenta> pedidos;
	private Vector<OVenta> oventas; // VA ESTO NO ?
	
	public Sistema()
	{
		rodamientosDTO = new Vector<RodamientoDTO>();
		rodamientos = new Vector<Rodamiento>();
		pedidos = new Vector<PedVenta>();
		oventas = new Vector<OVenta>();
	}
	
	public Vector<RodamientoDTO> getListaRodamientos()
	{
		for (Rodamiento rodamiento : rodamientos)
		{
			rodamientosDTO.add(rodamiento.getDTO());
		}
		return rodamientosDTO;
	}
	
	public void solicitarCotizacion()
	{
	
	}
	
	public void grabarNuevaCotizacion()
	{
	
	}
	
	public void buscarRodamento()
	{
	
	}
	
	public void agregarItem()
	{
	
	}
	
	public void leerXMLCotizacion()
	{
	
	}
	
	public void armarCotizacones()
	{
	
	}
	
	public void buscarOV()
	{
	
	}
	
	public void aceptarCotizacion()
	{
	
	}
	
	/*
	 * public XML leerXMLCotAceptadas() { } public XML leerXMLBultosAEnviar() { } public void borrarXMLPedidoCotizacion(XML xml) { } public void borrarXMLDeBultoAEnviar( XML xml) { }
	 */
	
	public void ActualizarStock(String codigoSKF, int cantidad, float precio)
	{
	
	}
	
	public void GenerarOrdenesDeCompra()// ACA VA listaXMLs
	{
		for (OVenta oventa : oventas)
		{
			pedidos.add(oventa.getPedidosVenta());
		}
		CCentral.getInstancia().generarOrdenesDeCompra(pedidos); // ESTO VA ASI????
	}
	
	public void PublicarListaDePreciosFinal()
	{
	
	}
	
	/*
	 * public void generarListaDePrecioProveedorAutomatica( XML archivoProveedor, int codigoProveedor) { }
	 */
	public void agregarItemAListaProveedor(int codigoProveedor, String codigoItem, float precio, String condiciones, boolean disponible, String codigoSKF, String Tipo)
	{
	
	}
}
