package RMI;

import java.util.ArrayList;
import java.util.List;

import Entities.Rodamiento;
import bean.RodamientoDTO;

//

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sistema.java
//  @ Date : 9/16/2015
//  @ Author : 
//
//

public class Sistema
{
	private List<RodamientoDTO> rodamientosDTO;
	private List<Rodamiento> rodamientos;
	
	public Sistema()
	{
		rodamientosDTO = new ArrayList<RodamientoDTO>();
		rodamientos = new ArrayList<Rodamiento>();
	}
	
	public List<RodamientoDTO> getListaRodamientos()
	{
		for (int i = 0; i < rodamientos.size(); i++)
		{
			rodamientosDTO.add(rodamientos.get(i).getDTO());
		}
		return rodamientosDTO;
	}
	
	public void solicitarCotizacion()
	{
	
	}
	
	public void grabarNuevaCotizacion()
	{
	
	}
	
	public void buscarRodamento()
	{
	
	}
	
	public void agregarItem()
	{
	
	}
	
	public void leerXMLCotizacion()
	{
	
	}
	
	public void armarCotizacones()
	{
	
	}
	
	public void buscarOV()
	{
	
	}
	
	public void aceptarCotizacion()
	{
	
	}
	
	/*
	 * public XML leerXMLCotAceptadas() { } public XML leerXMLBultosAEnviar() { } public void borrarXMLPedidoCotizacion(XML xml) { } public void borrarXMLDeBultoAEnviar( XML xml) { }
	 */
	
	public void ActualizarStock(String codigoSKF, int cantidad, float precio)
	{
	
	}
	/*
	 * public listasXML generarOrdenesDeCompra() { }
	 */
	
	public void PublicarListaDePreciosFinal()
	{
	
	}
	
	/*
	 * public void generarListaDePrecioProveedorAutomatica( XML archivoProveedor, int codigoProveedor) { }
	 */
	public void agregarItemAListaProveedor(int codigoProveedor, String codigoItem, float precio, String condiciones, boolean disponible, String codigoSKF, String Tipo)
	{
	
	}
}
